name: waisn-tech-tools
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=0.24.0=py37_0
  - beautifulsoup4=4.7.1=py37_1
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - cryptography=2.7=py37h1ba5d50_0
  - django=2.2.1=py37_0
  - ecdsa=0.13=py37_1
  - factory_boy=2.12.0=py37_0
  - faker=1.0.7=py37_0
  - future=0.17.1=py37_0
  - gmp=6.1.2=h6c8ec71_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1c=h7b6447c_1
  - pip=19.1.1=py37_0
  - pyasn1=0.4.5=py_0
  - pycparser=2.19=py37_0
  - pycryptodome=3.7.3=py37hb69a4c5_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - python-jose=3.0.1=py_0
  - pytz=2019.1=py_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - soupsieve=1.8=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - sqlparse=0.3.0=py_0
  - text-unidecode=1.2=py37_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - chardet==3.0.4
    - defusedxml==0.6.0
    - idna==2.8
    - oauthlib==3.0.2
    - pyjwt==1.7.1
    - python3-openid==3.1.0
    - requests==2.22.0
    - requests-oauthlib==1.2.0
    - social-auth-app-django==3.1.0
    - social-auth-core==3.2.0
    - transitions==0.6.9
    - urllib3==1.25.3
prefix: /opt/conda/envs/waisn-tech-tools
