name: waisn-tech-tools
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_0
  - beautifulsoup4=4.7.1=py37_1
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37hb5b8e2f_0
  - cryptography=2.6.1=py37ha12b0ac_0
  - django=2.1.4=py37_0
  - ecdsa=0.13=py37_1
  - factory_boy=2.11.1=py37_0
  - faker=1.0.1=py37_0
  - future=0.17.1=py37_0
  - gmp=6.1.2=hb37e062_1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1b=h1de35cc_1
  - pip=18.1=py37_0
  - pyasn1=0.4.5=py_0
  - pycparser=2.19=py37_0
  - pycryptodome=3.7.3=py37ha8bbb54_0
  - python=3.7.1=haf84260_7
  - python-dateutil=2.7.5=py37_0
  - python-jose=3.0.1=py_0
  - pytz=2018.7=py37_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.6.3=py37_0
  - six=1.12.0=py37_0
  - soupsieve=1.7.1=py37_0
  - sqlite=3.25.3=ha441bb4_0
  - text-unidecode=1.2=py37_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.32.3=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - chardet==3.0.4
    - defusedxml==0.6.0
    - idna==2.8
    - oauthlib==3.0.1
    - pyjwt==1.7.1
    - python-dotenv==0.10.2
    - python3-openid==3.1.0
    - requests==2.22.0
    - requests-oauthlib==1.2.0
    - social-auth-app-django==3.1.0
    - social-auth-core==3.1.0
    - transitions==0.6.9
    - urllib3==1.25.3
